language: python
cache: pip
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get -y install libmemcached-dev zlib1g-dev memcached
install: pip install tox-travis codecov
script:
  - tox -e lint
  - tox
notifications:
    email: false
after_success:
  - codecov